<?php
declare(strict_types=1);
/**
 * gen_base_seed.php — regenerate deploy/seed_base.sql from the current dev DB.
 * (Dev tool. Run against a dev database; NEVER commits real member data.)
 *
 *   php deploy/tools/gen_base_seed.php > deploy/seed_base.sql
 *
 * seed_base.sql is the GENERIC, PII-free base configuration every fresh install
 * needs: a core set of roles + the permission matrix, default system_config
 * option lists, and the FIRST program list. It seeds NO members, teams, events,
 * or any org-specific/secret values. The installer loads it right after
 * schema.sql + the migration baseline.
 */
require __DIR__ . '/../../vendor/autoload.php';
use App\Core\Config; use App\Core\Database;
Config::load(dirname(__DIR__, 2));
$pdo = Database::pdo();

// ── Which roles ship in the base install (generic to any FIRST org) ──────────
// Deliberately excludes TRC/dev-specific roles (Executive Director, Quartermaster,
// Scholarship Manager, TRCMS Project Contributor, Dev Team Leader). Admins add
// their own in Role Management.
$KEEP_ROLES = [
  'System Administrator','Admin','Mentor','Mentor - Lead','Mentor - Junior',
  'Youth Member','Parent','Volunteer','Team Leader','Default',
  'Inventory Manager','Purchasing Manager',
  'Event Check-In Station','Visitor Registration Station','Parts Room Station',
  'Generic Station','Team Tasks Station','FLL Attendance Station',
];

// ── system_config categories that hold org-specific or SECRET data → blanked ─
// Secrets MUST never enter the seed (smtp pass, github token, payment keys).
$BLANK_CONFIG = [
  'smtp'                => '{}',   // set in the setup wizard
  'github'              => '{}',   // no token
  'payments'            => '{"square_enabled":false,"paypal_enabled":false,"card_fee_percent":0}',
  'shipping_addresses'  => '[]',
  'social_media_links'  => '[]',
  'handbook'            => '{}',
  'incident_routing'    => '{}',
  'enrollment_fees'     => '[]',
  'enrollment_waivers'  => '{}',   // org supplies its OWN legal waiver text
  'volunteer_signup'    => '{"open":false}',  // org sets its own intro; closed until configured
];

// Categories NOT seeded at all — the app's code default is generic and current.
// (nav_layout here is TRC-customized; the built-in default sidebar is generic.)
$SKIP_CONFIG = ['nav_layout'];

// Genericize a few org-branded labels (the category KEY is internal and kept).
$LABEL_OVERRIDES = [
  'handbook'            => 'Handbook',
  'social_media_links'  => 'Social Media Links',
  'trc_task_categories' => 'Organization Task Categories',
];

function sqlstr(?string $s): string {
  if ($s === null) return 'NULL';
  return "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], $s) . "'";
}

$out = [];
$out[] = "-- TRCMS base configuration seed (GENERIC — no members, no org data, no secrets).";
$out[] = "-- Generated by deploy/tools/gen_base_seed.php. Loaded by the installer after";
$out[] = "-- schema.sql + the migration baseline. Idempotent-ish: run on a FRESH DB only.";
$out[] = "SET FOREIGN_KEY_CHECKS=0;";
$out[] = "";

// ── Roles (explicit ids kept so role_permissions can reference them) ─────────
$in = implode(',', array_map(fn($r) => $pdo->quote($r), $KEEP_ROLES));
$roles = $pdo->query("SELECT id,name,display_name,description,is_active FROM system_roles WHERE name IN ($in) ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);
$keepIds = array_map(fn($r) => (int)$r['id'], $roles);
$out[] = "-- Roles (" . count($roles) . ")";
$out[] = "INSERT INTO system_roles (id,name,display_name,description,is_active) VALUES";
$rows = [];
foreach ($roles as $r) {
  $rows[] = sprintf("  (%d,%s,%s,%s,%d)", $r['id'], sqlstr($r['name']), sqlstr($r['display_name']), sqlstr($r['description']), (int)$r['is_active']);
}
$out[] = implode(",\n", $rows) . ";";
$out[] = "";

// ── Role permissions (matrix for the kept roles only) ────────────────────────
$idList = implode(',', $keepIds);
$perms = $pdo->query("SELECT role_id,resource_key,level FROM role_permissions WHERE role_id IN ($idList) ORDER BY role_id,resource_key")->fetchAll(PDO::FETCH_ASSOC);
$out[] = "-- Role permissions (" . count($perms) . ")";
$chunks = array_chunk($perms, 200);
foreach ($chunks as $chunk) {
  $out[] = "INSERT INTO role_permissions (role_id,resource_key,level) VALUES";
  $rows = [];
  foreach ($chunk as $p) $rows[] = sprintf("  (%d,%s,%s)", (int)$p['role_id'], sqlstr($p['resource_key']), sqlstr($p['level']));
  $out[] = implode(",\n", $rows) . ";";
}
$out[] = "";

// ── system_config (generic option lists; org-specific/secret categories blanked) ──
$cfg = $pdo->query("SELECT category,label,`values` FROM system_config ORDER BY category")->fetchAll(PDO::FETCH_ASSOC);
$cfgHeaderIdx = count($out);
$out[] = "-- system_config (placeholder)";
$emitted = 0;
foreach ($cfg as $c) {
  if (in_array($c['category'], $SKIP_CONFIG, true)) continue;      // use the code default
  $val   = array_key_exists($c['category'], $BLANK_CONFIG) ? $BLANK_CONFIG[$c['category']] : (string)$c['values'];
  $label = $LABEL_OVERRIDES[$c['category']] ?? $c['label'];
  $out[] = sprintf("INSERT INTO system_config (category,label,`values`) VALUES (%s,%s,%s);",
    sqlstr($c['category']), sqlstr($label), sqlstr($val));
  $emitted++;
}
array_splice($out, $cfgHeaderIdx, 1, "-- system_config ($emitted categories; secrets/org-specific blanked, nav_layout uses code default)");
$out[] = "";

// ── Programs (FIRST starter list; FDP affiliation genericized) ───────────────
$out[] = "-- Programs (FIRST starter list). quick_attendance=1 = appears on the attendance kiosk.";
$out[] = "INSERT INTO programs (id,name,full_name,affiliation,age_range,status,display_order,quick_attendance) VALUES";
$out[] = "  (1,'FLLe','FIRST LEGO League Explore','FIRST LEGO League Explore','6-10','active',1,1),";
$out[] = "  (2,'FLLc','FIRST LEGO League Challenge','FIRST LEGO League Challenge','9-16','active',2,1),";
$out[] = "  (3,'FTC','FIRST Tech Challenge','FIRST Tech Challenge','12-18','active',3,0),";
$out[] = "  (4,'FRC','FIRST Robotics Competition','FIRST Robotics Competition','14-18','active',4,0),";
$out[] = "  (5,'FDP','FIRST Development Program','FIRST','10-18','active',5,0);";
$out[] = "";
$out[] = "SET FOREIGN_KEY_CHECKS=1;";

echo implode("\n", $out) . "\n";
