<?php
declare(strict_types=1);

namespace App\Analytics;

/**
 * MetricsRegistry — the canonical catalog of everything TRCMS can trend.
 *
 * This is metadata only: it describes each metric (what it is, where it comes
 * from, how it is captured, who may see it). The MetricCapture service turns
 * these definitions into metric_snapshots rows; the TrendsController serves
 * them to the Trends UI. Adding a new trend is (mostly) a new entry here.
 *
 * mechanism:
 *   'event'    — reconstructable from timestamped source rows (works
 *                retroactively as far back as the source dates go). Can be
 *                queried live OR snapshotted for speed.
 *   'snapshot' — a point-in-time state (current value) that is lost once the
 *                underlying rows change. Only accrues from capture turn-on, so
 *                the capture job must run on a schedule to build history.
 *
 * sensitivity: public | internal | pii | financial  (gates who may view; the
 * reports engine masks/omits by the viewer's field-tier entitlement).
 *
 * scope: the default breakdown a value is stored at. 'global' = whole program.
 * breakdowns: additional dimensions the metric can be sliced by.
 *
 * phase: 1 = MVP, 2 = charts/retention, 3 = advanced/dashboards.
 */
final class MetricsRegistry
{
    /**
     * @return array<string,array<string,mixed>> keyed by metric_key
     */
    public static function all(): array
    {
        return [

            // ---- People & membership --------------------------------------
            'active_youth' => [
                'label' => 'Active youth',
                'domain' => 'Membership',
                'mechanism' => 'snapshot',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['program', 'team', 'night', 'school'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => "members (member_type='youth', not archived) reconstructable per-season via member_season_participation / team_member_assignments",
            ],
            'active_mentors' => [
                'label' => 'Active mentors',
                'domain' => 'Membership',
                'mechanism' => 'snapshot',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['team', 'program'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => "members (member_type='mentor', not archived)",
            ],
            'total_members' => [
                'label' => 'Total active members',
                'domain' => 'Membership',
                'mechanism' => 'snapshot',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['member_type', 'team', 'program'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'members not archived',
            ],
            'new_joins' => [
                'label' => 'New members joined',
                'domain' => 'Membership',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['member_type', 'program', 'school', 'night'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'members.date_joined (or enrollments.date_enrolled per program)',
            ],
            'departures' => [
                'label' => 'Members departed',
                'domain' => 'Membership',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['member_type'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'members.archived_at (soft-delete = left org)',
            ],
            'net_growth' => [
                'label' => 'Net membership growth',
                'domain' => 'Membership',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['member_type'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'derived: new_joins - departures',
            ],
            'retention_rate' => [
                'label' => 'Cohort retention rate',
                'domain' => 'Membership',
                'mechanism' => 'event',
                'unit' => 'percent',
                'scope' => 'cohort',
                'breakdowns' => ['cohort_year', 'program'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'cohort by join-season x year-by-year membership from member_season_participation / team_member_assignments',
            ],
            'avg_tenure' => [
                'label' => 'Average tenure (years)',
                'domain' => 'Membership',
                'mechanism' => 'snapshot',
                'unit' => 'years',
                'scope' => 'global',
                'breakdowns' => ['member_type'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'now - members.date_joined for active members',
            ],
            'youth_mentor_ratio' => [
                'label' => 'Youth-to-mentor ratio',
                'domain' => 'Membership',
                'mechanism' => 'snapshot',
                'unit' => 'ratio',
                'scope' => 'global',
                'breakdowns' => ['team', 'program'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'derived: active_youth / active_mentors',
            ],

            // ---- Graduates & alumni ---------------------------------------
            'graduates' => [
                'label' => 'Graduates',
                'domain' => 'Alumni',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['season', 'program'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'member graduate date / season rollover (VERIFY exact column)',
            ],
            'alumni_total' => [
                'label' => 'Cumulative alumni',
                'domain' => 'Alumni',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => [],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'cumulative count of graduated members',
            ],
            'hof_inductions' => [
                'label' => 'Hall of Fame inductions',
                'domain' => 'Alumni',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => [],
                'sensitivity' => 'public',
                'phase' => 2,
                'source' => 'hall_of_fame induction date (VERIFY table)',
            ],

            // ---- Certifications -------------------------------------------
            'certs_added' => [
                'label' => 'Certifications recorded',
                'domain' => 'Certifications',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['certification'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'member_certifications.created_at (when awarded/entered)',
            ],
            'certs_completed' => [
                'label' => 'Certifications completed by youth',
                'domain' => 'Certifications',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['certification', 'team', 'program'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => "member_certifications.completed_date (status='completed')",
            ],
            'cert_completion_rate' => [
                'label' => 'Certification completion rate',
                'domain' => 'Certifications',
                'mechanism' => 'snapshot',
                'unit' => 'percent',
                'scope' => 'global',
                'breakdowns' => ['certification', 'team'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'completed / attempted member_certifications',
            ],
            'badges_earned' => [
                'label' => 'Badges earned',
                'domain' => 'Certifications',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['badge'],
                'sensitivity' => 'public',
                'phase' => 2,
                'source' => 'cert_member_badges.earned_date',
            ],

            // ---- Attendance & engagement ----------------------------------
            'attendance_rate' => [
                'label' => 'Attendance rate',
                'domain' => 'Engagement',
                'mechanism' => 'snapshot',
                'unit' => 'percent',
                'scope' => 'global',
                'breakdowns' => ['team', 'program', 'night'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'check-ins vs expected roster',
            ],
            'member_hours' => [
                'label' => 'Member hours logged',
                'domain' => 'Engagement',
                'mechanism' => 'event',
                'unit' => 'hours',
                'scope' => 'global',
                'breakdowns' => ['member_type', 'team', 'category'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'Time & Impact time entries (date x hours)',
            ],
            'mentor_hours' => [
                'label' => 'Mentor hours logged',
                'domain' => 'Engagement',
                'mechanism' => 'event',
                'unit' => 'hours',
                'scope' => 'global',
                'breakdowns' => ['team'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => "Time & Impact entries where member_type='mentor'",
            ],
            'outreach_hours' => [
                'label' => 'Community / outreach hours',
                'domain' => 'Engagement',
                'mechanism' => 'event',
                'unit' => 'hours',
                'scope' => 'global',
                'breakdowns' => ['team'],
                'sensitivity' => 'public',
                'phase' => 2,
                'source' => 'Time & Impact entries categorized outreach/service',
            ],

            // ---- Events ---------------------------------------------------
            'events_held' => [
                'label' => 'Events held',
                'domain' => 'Events',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['event_type', 'team'],
                'sensitivity' => 'public',
                'phase' => 1,
                'source' => 'events.start (past events)',
            ],
            'event_attendance' => [
                'label' => 'Event attendance',
                'domain' => 'Events',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['event_type', 'team'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'event check-ins / participants',
            ],
            'rsvp_conversion' => [
                'label' => 'RSVP-to-attend conversion',
                'domain' => 'Events',
                'mechanism' => 'snapshot',
                'unit' => 'percent',
                'scope' => 'global',
                'breakdowns' => ['event_type'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'attended / RSVP-attending',
            ],

            // ---- Visitors & recruitment funnel ----------------------------
            'visitors' => [
                'label' => 'Visitors logged',
                'domain' => 'Recruitment',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['source', 'school', 'program', 'night'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'visitors log date',
            ],
            'funnel_conversion' => [
                'label' => 'Visitor-to-enrollment conversion',
                'domain' => 'Recruitment',
                'mechanism' => 'snapshot',
                'unit' => 'percent',
                'scope' => 'global',
                'breakdowns' => ['source', 'program'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'recruitment funnel stages over time',
            ],
            'waitlist_size' => [
                'label' => 'Waitlist size',
                'domain' => 'Recruitment',
                'mechanism' => 'snapshot',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['program', 'night'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'waitlist rows currently pending (point-in-time)',
            ],
            'mentor_pipeline' => [
                'label' => 'Mentor pipeline prospects',
                'domain' => 'Recruitment',
                'mechanism' => 'snapshot',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['stage'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'mentor_prospects by stage',
            ],

            // ---- Inventory & assets ---------------------------------------
            'inventory_value' => [
                'label' => 'Total inventory value',
                'domain' => 'Inventory',
                'mechanism' => 'snapshot',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['category', 'location', 'team'],
                'sensitivity' => 'financial',
                'phase' => 1,
                'source' => 'sum(qty x unit cost) of inv_items (point-in-time)',
            ],
            'asset_value' => [
                'label' => 'Total asset value',
                'domain' => 'Inventory',
                'mechanism' => 'snapshot',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['category', 'team', 'location'],
                'sensitivity' => 'financial',
                'phase' => 1,
                'source' => 'sum of asset values (asset-typed inv_items)',
            ],
            'assets_acquired' => [
                'label' => 'Assets acquired',
                'domain' => 'Inventory',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['category', 'acquisition_type'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'inv_items acquired/created date for asset types',
            ],
            'repair_cost' => [
                'label' => 'Repair cost',
                'domain' => 'Inventory',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['category', 'asset'],
                'sensitivity' => 'financial',
                'phase' => 1,
                'source' => 'repair_tickets.repair_cost + repair_parts (by resolved date)',
            ],
            'repair_volume' => [
                'label' => 'Repairs logged',
                'domain' => 'Inventory',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['category'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'repair_tickets created date',
            ],
            'checkout_volume' => [
                'label' => 'Checkouts',
                'domain' => 'Inventory',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['category', 'team'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'checkout transactions date',
            ],
            'consumable_spend' => [
                'label' => 'Consumable / PO spend',
                'domain' => 'Inventory',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['category', 'vendor'],
                'sensitivity' => 'financial',
                'phase' => 2,
                'source' => 'inv_purchase_orders date x amount',
            ],

            // ---- Money in: grants / sponsors / donations / scholarships ----
            'funding_total' => [
                'label' => 'Total funding raised',
                'domain' => 'Fundraising',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['source_type', 'team', 'program'],
                'sensitivity' => 'financial',
                'phase' => 1,
                'source' => 'union of grants + donations + fundraising + payments by date',
            ],
            'funding_per_team' => [
                'label' => 'Funding per team',
                'domain' => 'Fundraising',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'team',
                'breakdowns' => ['team', 'source_type'],
                'sensitivity' => 'financial',
                'phase' => 1,
                'source' => 'grant_teams.amount_received (received_date) + team fundraising',
            ],
            'grants_awarded' => [
                'label' => 'Grants awarded ($)',
                'domain' => 'Fundraising',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['funder', 'team'],
                'sensitivity' => 'financial',
                'phase' => 1,
                'source' => "grant_teams.amount_received where outcome='awarded' (received_date)",
            ],
            'grant_win_rate' => [
                'label' => 'Grant win rate',
                'domain' => 'Fundraising',
                'mechanism' => 'event',
                'unit' => 'percent',
                'scope' => 'global',
                'breakdowns' => ['funder'],
                'sensitivity' => 'financial',
                'phase' => 2,
                'source' => 'awarded / (awarded+declined) grant_teams by submitted_date',
            ],
            'donations_total' => [
                'label' => 'Donations received',
                'domain' => 'Fundraising',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['category'],
                'sensitivity' => 'financial',
                'phase' => 1,
                'source' => 'inv_fundraising_donations.received_amount (received_date)',
            ],
            'donation_count' => [
                'label' => 'Donation count',
                'domain' => 'Fundraising',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['category'],
                'sensitivity' => 'internal',
                'phase' => 1,
                'source' => 'inv_fundraising_donations rows with received_date',
            ],
            'sponsors_active' => [
                'label' => 'Active sponsors',
                'domain' => 'Fundraising',
                'mechanism' => 'snapshot',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['tier', 'scope'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'sponsors currently active (point-in-time)',
            ],
            'sponsor_dollars' => [
                'label' => 'Sponsor dollars',
                'domain' => 'Fundraising',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['tier', 'team'],
                'sensitivity' => 'financial',
                'phase' => 2,
                'source' => 'sponsor contributions by date',
            ],
            'scholarships_awarded' => [
                'label' => 'College scholarships awarded ($)',
                'domain' => 'Scholarships',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['college', 'season'],
                'sensitivity' => 'financial',
                'phase' => 2,
                'source' => 'college_* awarded amount by date',
            ],
            'payments_collected' => [
                'label' => 'Payments collected',
                'domain' => 'Payments',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['provider', 'source_type'],
                'sensitivity' => 'financial',
                'phase' => 1,
                'source' => "payments.amount where status='paid' (paid_at)",
            ],

            // ---- Money out & financial health -----------------------------
            'total_spend' => [
                'label' => 'Total spend',
                'domain' => 'Finance',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['category', 'team'],
                'sensitivity' => 'financial',
                'phase' => 2,
                'source' => 'team_adhoc_expenses + POs + QuickBooks import by date',
            ],
            'team_expenses' => [
                'label' => 'Team expenses',
                'domain' => 'Finance',
                'mechanism' => 'event',
                'unit' => 'currency',
                'scope' => 'team',
                'breakdowns' => ['team'],
                'sensitivity' => 'financial',
                'phase' => 1,
                'source' => 'team_adhoc_expenses.amount (expense_date)',
            ],
            'cost_per_member' => [
                'label' => 'Cost per member',
                'domain' => 'Finance',
                'mechanism' => 'snapshot',
                'unit' => 'currency',
                'scope' => 'global',
                'breakdowns' => ['team'],
                'sensitivity' => 'financial',
                'phase' => 3,
                'source' => 'derived: total_spend / total_members',
            ],

            // ---- Operations & program health ------------------------------
            'reservations_volume' => [
                'label' => 'Reservation requests',
                'domain' => 'Operations',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['status'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'reservations created date',
            ],
            'feedback_opened' => [
                'label' => 'Feedback items opened',
                'domain' => 'Operations',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['type'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'feedback created date',
            ],
            'repair_backlog' => [
                'label' => 'Open repair backlog',
                'domain' => 'Operations',
                'mechanism' => 'snapshot',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => ['category'],
                'sensitivity' => 'internal',
                'phase' => 2,
                'source' => 'repair_tickets currently open (point-in-time)',
            ],
            'emails_sent' => [
                'label' => 'Emails sent',
                'domain' => 'Operations',
                'mechanism' => 'event',
                'unit' => 'count',
                'scope' => 'global',
                'breakdowns' => [],
                'sensitivity' => 'internal',
                'phase' => 3,
                'source' => 'communications send log date',
            ],
        ];
    }

    /** Metric keys that must be captured on a schedule (state is otherwise lost). */
    public static function snapshotKeys(): array
    {
        return array_keys(array_filter(
            self::all(),
            static fn (array $m): bool => ($m['mechanism'] ?? '') === 'snapshot'
        ));
    }

    public static function get(string $key): ?array
    {
        return self::all()[$key] ?? null;
    }
}
